### ISSUE TITLE
support vue.js types

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [sjrd/scala-js-ts-importer#51]
we suggest `vue.js` as test case: https://github.com/vuejs/vue/tree/dev/types

none of theses types can be currently converted by `scala-js-ts-importer`

**Comment by sjrd** [comment]
Thank you for the report. However, this is pretty vague as a filed issue. Instead, issues should be filed separately for individual features, so that things are actionable, one commit at a time fixing one filed issue at a time. I will therefore close this issue, and I encourage you to file one issue per one missing feature instead.
